environment:
  #CMAKE_PREFIX_PATH: "C:\\Qt\\5.11.1\\msvc2015"
  #
  #QTDIR: "C:\\Qt\\5.11.1\\msvc2015"
  #GENERATOR: "Visual Studio 14 2015"
  QTDIR: "C:\\Qt\\5.11.1\\mingw53_32"
  GENERATOR: "MinGW Makefiles"
  
image:
  - "Visual Studio 2015"


build_script:
  - cmd: |-
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=C:\MinGW\bin;%PATH%
      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      mkdir build
      cd build
      cmake -G "%GENERATOR%" ..
      REM cmake --build . --target ALL_BUILD
      cmake --build . 

      dumpbin /dependents cmake-qtcore-example

      set PATH=%QTDIR%\bin;%PATH%
      rem Debug\cmake-qtcore-example
      cmake-qtcore-example
