environment:
  QTDIR: "C:\\Qt\\5.11.1\\msvc2015"
  CMAKE_PREFIX_PATH: "C:\\Qt\\5.11.1\\msvc2015"
  
image:
  - "Visual Studio 2015"


build_script:
  - cmd: |-
      mkdir build
      cd build
      cmake -G "Visual Studio 14 2015" ..
      cmake --build . --target ALL_BUILD
      cmake-qtcore-example
